### ISSUE TITLE
No information about "no wait" state

### ISSUE THREAD

**Issue by egor-rogov** [postgrespro/pg_wait_sampling#10]
The case of _not waiting_ (`wait_event_info == 0`) is no less important than the case of waiting. Absence of "no wait" counts in profile make it impossible to compare waiting time to active time.

**Comment by egor-rogov** [comment]
Looks like this requires another algorithm of iterating over backends, probably the same as in `pg_stat_activity`. Just commenting out `if (proc->wait_event_info == 0) continue;` in `probe_waits()` leaves a lot of empty rows in profile from some processes which are not listed in `pg_stat_activity`.

**Comment by legrandlegrand** [comment]
removing `&& proc->wait_event_info`	in	`if (proc != NULL && proc->pid != 0 && proc->wait_event_info)` from `pg_wait_sampling_get_current()` gives the same for current view.

Joining this current waits with pg_stat_activity on pid, removes the extra pids, but **lines that are not in state='active' are also displayed ...**

finally, the following statement (pgss join is just for testing) 
```
SELECT
	pgsa.usename,
	pgsa.application_name,
	pgsa.client_addr,
	pgsa.client_port,
	pgsa.backend_start,
	pgsa.backend_type,
	pgsa.state,
	pgwsc.pid,
	pgsa.query_start,
	pgsa.wait_event_type AS acti_evt_type,
	pgsa.wait_event AS acti_evt,
	pgwsc.event_type,
	pgwsc.event,
	pgsa.query AS top_level_query,
	pgwsc.queryid,
	pgss.query,
	pgss.calls
FROM
	public.pg_wait_sampling_current pgwsc
	INNER JOIN pg_catalog.pg_stat_activity pgsa 
	 ON pgwsc.pid = pgsa.pid
	LEFT OUTER JOIN public.pg_stat_statements pgss  
	 ON pgwsc.queryid = pgss.queryid
WHERE
	pgsa.state = 'active'
```

is still very usefull to monitor low level queries (from pl/pgsql blocks, triggers and so on). Except that events mismatch between thoses from pg_stat_activity and thoses from pg_wait_sampling_current is quite confusing ;o(

Wouldn't a custom (or a core) pg_stat_activity view build with a native queryid be a better solution ?

Regards
PAscal
