### ISSUE TITLE
Queryid is always 0 with utility statements

### ISSUE THREAD

**Issue by legrandlegrand** [postgrespro/pg_wait_sampling#11]
Hello,

Queryid for utility statements are 0 in pg_stat_statements until their end.
Maybe that queryid should be computed in pg_wait_sampling 
using the same pgss_hash_string() function.

Regards
PAscal

**Comment by keremet** [comment]
@legrandlegrand , Hello, could you explain how to reproduce the error step by step?

**Comment by Medvecrab** [comment]
Fixed in v1.1.6
