### ISSUE TITLE
Question: Installation for Postgres-12

### ISSUE THREAD

**Issue by gowtham500** [postgrespro/pg_wait_sampling#16]
Hello team,

1. how do you install the extension for postgresql-12. 
2. I downloaded the releases package. Untar and copied the contents onto /usr/pgsql-12/share/extensions/
3. When I restart postgresql by updating config, shared_preload_libraries='pg_wait_sampling'
postgres does not start with error "unable to find file or directory with name pg_wait_sampling"
4. Can you please share a step by step procedure.

**Comment by maksm90** [comment]
Hi @gowtham500 !
If you have loaded source code from release link in current repository you have to build and install extension using `make install` command as described in [README](https://github.com/postgrespro/pg_wait_sampling#installation) (all successive commands after `git clone ...`) previously installing dev package of your PostgreSQL distributive.

**Comment by maksm90** [comment]
Hi @gowtham500 !

Did the suggestion above help you? Can I close issue?

**Comment by gowtham500** [comment]
Yes thanks 👍
