### ISSUE TITLE
instalation error

### ISSUE THREAD

**Issue by ramazangok** [postgrespro/pg_wait_sampling#19]
Hi All,

I'm having issue about  installing like  below step.  Postgresql 11.7 

-bash-4.2$ make USE_PGXS=1
gcc -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic -DLINUX_OOM_SCORE_ADJ=0 -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Wendif-labels -Wmissing-format-attribute -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard -fPIC -I. -I. -I/usr/include/pgsql/server -I/usr/include/pgsql/internal -D_GNU_SOURCE -I/usr/include/libxml2   -c -o pg_wait_sampling.o pg_wait_sampling.c
pg_wait_sampling.c:13:33: fatal error: access/htup_details.h: No such file or directory
 #include "access/htup_details.h"
                                 ^
compilation terminated.
make: *** [pg_wait_sampling.o] Error 1

**Comment by maksm90** [comment]
Hi!

`access/htup_details.h` is the server's header file and have to be inside `/usr/include/pgsql/server` directory. I think the source of this issue is absence of `postgresql-dev` package as in #20

**Comment by maksm90** [comment]
Hi @ramazangok !

Could you give me any feedback on your issue? Can I close it?
