### ISSUE TITLE
compile error

### ISSUE THREAD

**Issue by ramazangok** [postgrespro/pg_wait_sampling#20]
Hi All,

I am  taking like  below error.  Could  you make a suggestion to resolve that error

[root@replica pg_wait_sampling-1.1]$echo $PATH
/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/root/bin:/usr/pgsql-11/bin:/usr/pgsql-11/bin:/usr/pgsql-11/bin/pg_config

[root@replica pg_wait_sampling-1.1]$ sudo make USE_PGXS=1 install
make: pg_config: Command not found
make: *** No rule to make target `install'.  Stop.

**Comment by maksm90** [comment]
Hi!

Last two terms in $PATH variable `/usr/pgsql-11/bin:/usr/pgsql-11/bin/pg_config` are redundant. `pg_config` tool is in `postgresql-server-dev` package that not installed with standard `postgresql-server` one. So I recommend you to 1) check existence of `pg_config` binary inside `/usr/pgsql-11/bin`, 2) install `postgresql-server-dev` if it's not exist there, 3) refine $PATH definition

**Comment by maksm90** [comment]
Hi @ramazangok !

Did the suggestions above help you? Could I close the issue?

**Comment by jrouhaud** [comment]
Note also that your problem is likely that the $PATH is different when using `sudo`.  You could use the `-E` sudo option to preserve your environment variables.
