### ISSUE TITLE
Debian package

### ISSUE THREAD

**Issue by anayrat** [postgrespro/pg_wait_sampling#21]
Hello,

It would be great to have this extension in PGDG's debian packages.

@df7cb there is github release tag and test suite. Do you need something else for the packging?

Thanks!

**Comment by df7cb** [comment]
More time... I'm already maintaining over 100 packages, maybe someone else could do the Debian part and I'll bring it to apt.postgresql.org.

**Comment by anayrat** [comment]
I forgot the issue was still open after packages were available. We can close it now, thanks!
