### ISSUE TITLE
Select from pg_available_extensions shows installed_version 1.1, expected 1.1.1

### ISSUE THREAD

**Issue by banlex73** [postgrespro/pg_wait_sampling#27]
Hi there
Just installed the latest version from source
running select * from pg_available_extensions where name ='pg_wait_sampling'
 name       | default_version | installed_version |                 comment
------------------+-----------------+-------------------+------------------------------------------
 pg_wait_sampling | 1.1             | 1.1               | sampling based statistics of wait events

Is it as expected? not 1.1.1 version?

**Comment by ololobus** [comment]
Hi @banlex73, yes it is expected. First two digits (\*.\*) are reserved for Postgres extension versioning. So they are incremented only if there were any changes in the extension SQL scripts, i.e. user-visible functions/schema.

The last digit (e.g. 1.1.\*) is used to indicate only **binary** changes of the extension shared library. So it is only visible in GitHub releases and packages.

In the 1.1.1 release, for example, if we'd put 1.1.1 into pg_wait_sampling.control file, then we had to put an empty SQL upgrade script, so Postgres was able to upgrade from 1.1 to 1.1.1. Even if there were no changes in SQL.

This topic has been partially discussed here: https://github.com/postgrespro/pg_wait_sampling/pull/23#issuecomment-646146057

Do you have any issues with this versioning scheme?

**Comment by banlex73** [comment]
Thank you Alexey for the explanation. No, I don't have any issues with
versioning..

чт, 22 жовт. 2020 о 08:07 Alexey Kondratov <notifications@github.com> пише:

**Comment by ololobus** [comment]
OK, then I'm closing this issue. Feel free to open a new one if it's needed.
