### ISSUE TITLE
When listing extensions 1.1 is shown as version instead of 1.1.3

### ISSUE THREAD

**Issue by dreis2211** [postgrespro/pg_wait_sampling#36]
Hi,

when listing installed extensions the version is showing as `1.1` although `1.1.3` should be installed.
```
                                            List of installed extensions
        Name        | Version |   Schema   |                              Description                               
--------------------+---------+------------+------------------------------------------------------------------------
 pg_wait_sampling   | 1.1     | public     | sampling based statistics of wait events
...
(7 rows)
```
Could we list the complete version with patch versions included?

Cheers,
Christoph

**Comment by rjuju** [comment]
That's the intended behavior.  The extension only has 2 digits to track the SQL-level changes, while the 3rd digits is bumped for C level only, which only impact the shared lib (and thus a postgres restart).

**Comment by dreis2211** [comment]
Okay - we got confused by the difference between debian package and actual schema. And other extensions had the patch version included. But if not possible, feel free to close it.

**Comment by anayrat** [comment]
Thanks @rjuju , I close it.
