### ISSUE TITLE
Requested shared memory is always less than captured

### ISSUE THREAD

**Issue by maksm90** [postgrespro/pg_wait_sampling#41]
Starting from commit https://github.com/postgres/postgres/commit/cdbc0ca48ca shared preload libraries are become to initialize before `MaxBackends` global variable setup. This might lead to invalid calculation of requested shared memory size if this calculation is based on max number of possible backend processes in postgres instance. For `pg_wait_sampling` module the size calculation of queryId shared memory [follows](https://github.com/postgrespro/pg_wait_sampling/blob/master/pg_wait_sampling.c#L259-L260) this rule, i.e. it uses `MaxBackends` value. As result, for this shared memory fragment we request zero size (UPD. not zero but [NUM_AUXILIARY_PROCS + max_prepared_xacts](https://github.com/postgrespro/pg_wait_sampling/blob/master/pg_wait_sampling.c#L79-L82) size) but later we assign non-zero memory (with already initialized `MaxBackends` value) for this purpose. Such behavior might incur future occurrences of `out of shared memory` errors.

The hackers [thread](https://www.postgresql.org/message-id/flat/20220323045229.i23skfscdbvrsuxa%40jrouhaud#13ce8209a711e1937527f4c38dcb1bb6) have to help in finding of possible solution.

**Comment by rjuju** [comment]
FTR I noticed this problem a few days ago, which is mostly why I sent this email.  I was waiting for an agreement on a new hook on the mailing list to send a PR here.

Note that even with the new hook the memory requested during `_PG_init` will still be wrong on pre pg15 version, so I can send a patch for that already if you want (which would be computing what should be MaxBackends, even if it can be underestimated if later modules changes some GUC, as I'm already doing in e.g. https://github.com/powa-team/pg_stat_kcache/blob/master/pg_stat_kcache.c#L672-L673)

**Comment by maksm90** [comment]
Hi @rjuju !

> FTR I noticed this problem a few days ago, which is mostly why I sent this email. I was waiting for an agreement on a new hook on the mailing list to send a PR here.

Thanks for working on this.

> Note that even with the new hook the memory requested during _PG_init will still be wrong on pre pg15 version, so I can send a patch for that already if you want (which would be computing what should be MaxBackends, even if it can be underestimated if later modules changes some GUC, as I'm already doing in e.g. https://github.com/powa-team/pg_stat_kcache/blob/master/pg_stat_kcache.c#L672-L673)

Yes, you can if it's not hard to you.

**Comment by rjuju** [comment]
Sure!

Note that we're now two people thinking that the current GetMaxBackends() approach doesn't provide a clean basis to fix this problem so I don't think that there will be something available in pg15 for entirely fix the problem.
