### ISSUE TITLE
PostgreSQL 15 support

### ISSUE THREAD

**Issue by devrimgunduz** [postgrespro/pg_wait_sampling#59]
Hi,

1.1.3 does not compile against v15 rc1. v15.0 is due in two weeks. Can you please take a look? Thanks!

> /usr/lib64/ccache/clang -Wno-ignored-attributes -fno-strict-aliasing -fwrapv -Wno-unused-command-line-argument -Wno-compound-token-split-by-macro -O2  -I. -I./ -I/usr/pgsql-15/include/server -I/usr/pgsql-15/include/internal  -D_GNU_SOURCE -I/usr/include/libxml2  -I/usr/include -flto=thin -emit-llvm -c -o compat.bc compat.c
> collector.c: In function 'send_history':
> collector.c:223:21: error: too few arguments to function 'shm_mq_send'
>   223 |         mq_result = shm_mq_send(mqh, sizeof(count), &count, false);
>       |                     ^~~~~~~~~~~
> In file included from collector.c:22:
> /usr/pgsql-15/include/server/storage/shm_mq.h:72:22: note: declared here
>    72 | extern shm_mq_result shm_mq_send(shm_mq_handle *mqh,
>       |                      ^~~~~~~~~~~
> collector.c:233:29: error: too few arguments to function 'shm_mq_send'
>   233 |                 mq_result = shm_mq_send(mqh,
>       |                             ^~~~~~~~~~~
> /usr/pgsql-15/include/server/storage/shm_mq.h:72:22: note: declared here
>    72 | extern shm_mq_result shm_mq_send(shm_mq_handle *mqh,
>       |                      ^~~~~~~~~~~
> collector.c: In function 'send_profile':
> collector.c:258:21: error: too few arguments to function 'shm_mq_send'
>   258 |         mq_result = shm_mq_send(mqh, sizeof(count), &count, false);
>       |                     ^~~~~~~~~~~
> /usr/pgsql-15/include/server/storage/shm_mq.h:72:22: note: declared here
>    72 | extern shm_mq_result shm_mq_send(shm_mq_handle *mqh,
>       |                      ^~~~~~~~~~~
> collector.c:269:29: error: too few arguments to function 'shm_mq_send'
>   269 |                 mq_result = shm_mq_send(mqh, sizeof(ProfileItem), item, false);
>       |                             ^~~~~~~~~~~
> /usr/pgsql-15/include/server/storage/shm_mq.h:72:22: note: declared here
>    72 | extern shm_mq_result shm_mq_send(shm_mq_handle *mqh,
>       |                      ^~~~~~~~~~~
> collector.c: In function 'collector_main':
> collector.c:345:9: error: too few arguments to function 'InitPostgres'
>   345 |         InitPostgres(NULL, InvalidOid, NULL, InvalidOid, NULL, false);
>       |         ^~~~~~~~~~~~
> In file included from collector.c:17:
> /usr/pgsql-15/include/server/miscadmin.h:460:13: note: declared here
>   460 | extern void InitPostgres(const char *in_dbname, Oid dboid,
>       |             ^~~~~~~~~~~~
> make[1]: *** [<builtin>: collector.o] Error 1
> make[1]: *** Waiting for unfinished jobs....
> collector.c:223:59: error: too few arguments to function call, expected 5, have 4
>         mq_result = shm_mq_send(mqh, sizeof(count), &count, false);
>                     ~~~~~~~~~~~                                  ^
> /usr/pgsql-15/include/server/storage/shm_mq.h:72:22: note: 'shm_mq_send' declared here
> extern shm_mq_result shm_mq_send(shm_mq_handle *mqh,
>                      ^
> collector.c:236:14: error: too few arguments to function call, expected 5, have 4
>                                                                 false);
>                                                                      ^
> /usr/pgsql-15/include/server/storage/shm_mq.h:72:22: note: 'shm_mq_send' declared here
> extern shm_mq_result shm_mq_send(shm_mq_handle *mqh,
>                      ^
> collector.c:258:59: error: too few arguments to function call, expected 5, have 4
>         mq_result = shm_mq_send(mqh, sizeof(count), &count, false);
>                     ~~~~~~~~~~~                                  ^
> /usr/pgsql-15/include/server/storage/shm_mq.h:72:22: note: 'shm_mq_send' declared here
> extern shm_mq_result shm_mq_send(shm_mq_handle *mqh,
>                      ^
> collector.c:269:64: error: too few arguments to function call, expected 5, have 4
>                 mq_result = shm_mq_send(mqh, sizeof(ProfileItem), item, false);
>                             ~~~~~~~~~~~                                      ^
> /usr/pgsql-15/include/server/storage/shm_mq.h:72:22: note: 'shm_mq_send' declared here
> extern shm_mq_result shm_mq_send(shm_mq_handle *mqh,
>                      ^
> collector.c:345:62: error: too few arguments to function call, expected 7, have 6
>         InitPostgres(NULL, InvalidOid, NULL, InvalidOid, NULL, false);
>         ~~~~~~~~~~~~                                                ^
> /usr/pgsql-15/include/server/miscadmin.h:460:13: note: 'InitPostgres' declared here
> extern void InitPostgres(const char *in_dbname, Oid dboid,
>             ^
>

**Comment by maksm90** [comment]
Hi!
Actual master branch successfully builds with pg15_rc1.
@shinderuk could you tag the HEAD of master branch by new version (and fill corresponding release entry) to make available extension to build with upcoming pg15?

**Comment by shinderuk** [comment]
@devrimgunduz @df7cb I've just tagged v1.1.4 release that is compatible with PostgreSQL 15. And also updated the "debian" branch.

**Comment by df7cb** [comment]
Looks good, thanks!
