### ISSUE TITLE
Поправьте описание ручной сборки

### ISSUE THREAD

**Issue by shab2** [postgrespro/pg_wait_sampling#65]
$ git clone https://github.com/postgrespro/pg_wait_sampling.git
$ cd pg_wait_sampling
$ make USE_PGXS=1
$ sudo make USE_PGXS=1 install

здесь прописать в shared_preload_library
переподнять постгрес, вот тогда ваш инстал чек не будет выдавать ошибки. А то, что вы выше написали, то читают редко

$ make USE_PGXS=1 installcheck
$ psql DB -c "CREATE EXTENSION pg_wait_sampling;"

**Comment by shinderuk** [comment]
Готово. Спасибо!
