### ISSUE TITLE
New release with PG16 support

### ISSUE THREAD

**Issue by df7cb** [postgrespro/pg_wait_sampling#68]
The code has been fixed, could a new version be tagged to update the Debian packages?

**Comment by devrimgunduz** [comment]
Ping. Release is due in two days.

**Comment by df7cb** [comment]
Ping from Debian as well.

**Comment by devrimgunduz** [comment]
Ping

**Comment by devrimgunduz** [comment]
ping.

**Comment by shinderuk** [comment]
Hi! Just tagged v1.1.5. Sorry for being late.

**Comment by devrimgunduz** [comment]
Thanks a lot!

**Comment by df7cb** [comment]
Thanks!
